#! /bin/zsh

case $OSTYPE in
    linux*)                     # Linux generic
 	      export X11HOME=/usr/X11R6
 	      ;;
    darwin*)                    # OSX
 	      export X11HOME=/usr/X11
 	      ;;
    *)
 	      ;;
esac

# set path
typeset -U path
path=(
    $HOME/bin(N-/)
    $ZPLUG_HOME/bin(N-/)
    $HOME/.local/bin(N-/)
    /usr/local/opt/coreutils/libexec/gnubin(N-/)
    /opt/local/sbin(N-/)
    /opt/local/bin(N-/)
    /opt/sbin(N-/)
    /opt/bin(N-/)
    /usr/local/sbin(N-/)
    /usr/local/bin(N-/)
    /usr/sbin(N-/)
    /usr/bin(N-/)
    /sbin(N-/)
    /bin(N-/)
    /usr/ucb(N-/)
    /usr/games(N-/)
    $X11HOME/bin(N-/)
    $path
    /home/linuxbrew/.linuxbrew/sbin(N-/)
    /home/linuxbrew/.linuxbrew/bin(N-/)
)

# set manpath
typeset -U manpath
manpath=(
    /usr/local/opt/coreutils/libexec/gnuman(N-/)
    /Library/Developer/CommandLineTools/usr/share/man(N-/)
    /opt/local/share/man(N-/)
    /opt/share/man(N-/)
    /usr/local/share/man(N-/)
    /usr/share/man(N-/)
    $X11HOME/share/man(N-/)
    $manpath
    /home/linuxbrew/.linuxbrew/share/man(N-/)
)
export MANPATH

# set fpath
typeset -U fpath
fpath=(
    $fpath
    $HOME/.local/share/zsh/functions(N-/)
    $HOME/.local/share/zsh/completions(N-/)
    /home/linuxbrew/.linuxbrew/share/zsh/site-functions(N-/)
)
export FPATH

eval "$(sheldon source)"

export STARSHIP_CONFIG=~/.config/starship/starship.toml
eval "$(starship init zsh)"
