;;; ~/.emacs.d/Cask

(source gnu)
(source melpa)
(source marmalade)

;; setup
(depends-on "init-loader")
(depends-on "exec-path-from-shell")

;; color
(depends-on "color-theme-solarized")

;; popwin
(depends-on "popwin")

;; direx
(depends-on "direx")

;; helm
(depends-on "helm")
(depends-on "helm-ag")

;; git
(depends-on "magit")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "git-gutter")
(depends-on "git-gutter-fringe")

;; wgrep
(depends-on "wgrep")

;; auto-complete
(depends-on "auto-complete")
(depends-on "popup")

;; ruby
(depends-on "ruby-mode")
(depends-on "ruby-compilation")
(depends-on "ruby-electric")
(depends-on "ruby-end")
(depends-on "inf-ruby")

;; misc major mode
(depends-on "php-mode")
(depends-on "scss-mode")
(depends-on "yaml-mode")


(depends-on "color-moccur")

;; Local Variables:
;; mode: emacs-lisp
;; coding: utf-8
;; indent-tabs-mode: nil
;; End:

;;; Cask ends here
